### ISSUE TITLE
Tetraploid

### ISSUE THREAD

**Issue by huw143** [leticia-lara/PM_data#1]
Hi Leticia,

I did not see any tetraploid genotypic code (0, 1, 2, 3, 4) in your molecular marker, not sure how you conduct the tetraploid genomic selection models using the R scripts of Bayesian_models 

Thank you,

HU

**Comment by leticia-lara** [comment]
Hi @huw143,

Thanks for your message. There are tetraploid markers in the population but indeed they are not majority of the markers (1,223 markers out of 41,424 markers). To compare tetraploid vs diploid dosage models, we needed to give them the same proportion of occurrence. This indicates that tetraploid dosage would be essential in populations/traits with high proportion of heterozygous genotypes, but diploid dosage is as efficient as the tetraploid dosage for populations/traits with high proportion of homozygous genotypes (which is expected). I'm happy in scheduling a half-an-hour chat with you to go through this topics if you have any question left. Just send me an email at llara@abacusbio.com.

Best regards
LL

**Comment by huw143** [comment]
Great thanks to Leticia for your generous helps to explain the tetraploid GS models and share the tetraploid data.  I learned something very beneficial for my alfalfa project since the Tetraploid GS model is more superior than Diploid GS models.  This manuscript would be a great reference for anyone working on the cultivated alfalfa GS projects. 

All the best,

Hu

**Comment by leticia-lara** [comment]
Thanks for the feedback Hu!
I will close this issue now! Please, contact me if you need any other help.

Best regards
LL

**Comment by huw143** [comment]
Hi Leticia,

Sorry to bother you again,

When I run the Bayesian_models.R from your github account using the
filtered data (*Including diploid and tetraploid data*) you provided for
me. I met the following problem:

The code here gave me a error:

count = 1
for (i in 1:s) {
y_pred_matrix[,i] = list_for[[i]][-1]
} Error in y_pred_matrix[, i] <- list_for[[i]][-1] :
  number of items to replace is not a multiple of replacement length When I
checked the length of y_pred_matrix[,i] and list_for[[i]][-1], it gave me
the results as follows:

> length(y_pred_matrix[,i])
[1] 2650
> length(list_for[[i]][-1])
[1] 5300

I also checked the list_for[[i]][-1], it included the 100 list from the
previous results.

I checked everything, which is all right. I wonder do you meet this problem
before, and how to fix this.

Sorry I am not an expert in R and tried my best to learn R.

Thanks,

Hu

**Comment by huw143** [comment]
Hi Leticia,
Please ignore the problem, I figured it out already.
Cheers,
Hu
